# Generated by Django 2.2.2 on 2019-07-04 13:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='customer_id')),
                ('password', models.CharField(max_length=256, verbose_name='password')),
                ('nickname', models.CharField(max_length=50, verbose_name='nickname')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone_number')),
            ],
        ),
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('store_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='store_id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='SPU',
            fields=[
                ('SPU_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='SPU_id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.store')),
                ('catagories', models.ManyToManyField(to='main.catagory')),
                ('spec', models.ManyToManyField(to='main.specification')),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('SKU_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='SKU_id')),
                ('price', models.IntegerField(verbose_name='price')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SPU')),
                ('options', models.ManyToManyField(to='main.option')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='order_id')),
                ('price', models.IntegerField(verbose_name='price')),
                ('create_time', models.TimeField(verbose_name='create_time')),
                ('payment_time', models.TimeField(verbose_name='payment_time')),
                ('confirm_time', models.TimeField(verbose_name='confirm_time')),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.specification'),
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='number')),
                ('toCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='main.customer')),
                ('toSKU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SKU')),
            ],
        ),
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(verbose_name='URL')),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SKU')),
            ],
        ),
    ]
