# Generated by Django 2.2.2 on 2019-07-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190709_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.AddField(
            model_name='customer',
            name='openid',
            field=models.CharField(default='', max_length=100, verbose_name='openid'),
        ),
        migrations.AlterField(
            model_name='img',
            name='URL',
            field=models.CharField(max_length=200, verbose_name='URL'),
        ),
    ]
